
application: ironnews-crawler1
version: v1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico
  mime_type: image/vnd.microsoft.icon
- url: /robots.txt 
  static_files: public/robots.txt 
  upload: public/robots.txt 
- url: /test
  script: test.py
- url: /.*
  script: app.py
