
application: ironnews-crawler1
version: v1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico
  mime_type: image/vnd.microsoft.icon
- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt
- url: /status
  script: status.py
- url: /dump
  script: dump.py
- url: /crawler/google-news
  script: crawler_google_news.py
- url: /feeder/google-news
  script: feeder_google_news.py
- url: /cleaner
  script: cleaner.py
- url: /.*
  script: app.py
